window.DHE_SEO_CONFIG = {
  siteUrl: "https://dreamhomeenterprises.in/",
  businessName: "Dream Home Enterprises",
  description:
    "Premium tile store and bathware showroom in Jammalamadugu, Kadapa District, Andhra Pradesh. Serving Jammalamadugu, Proddatur, and nearby areas with floor tiles, wall tiles, vitrified tiles, and sanitary ware.",
  streetAddress: "M.P.D.O Office Road",
  locality: "Jammalamadugu",
  region: "Andhra Pradesh",
  postalCode: "516434",
  country: "IN",
  latitude: 14.8495985,
  longitude: 78.3839138,
  phone: "+919490606528",
  phoneAlt: "+917036338999",
  email: "dreamhomeenterprises.jmd@gmail.com",
  instagram: "https://instagram.com/dreamhome.tiles",
  mapsUrl: "https://maps.app.goo.gl/wJz6Hptb7gxwZo6w9",
  logoPath: "logow.png",
  priceRange: "₹₹",
  areaServed: [
    "Jammalamadugu",
    "Proddatur",
    "Kadapa",
    "Kadapa District",
    "Andhra Pradesh",
    "Mydukur",
    "Pulivendula",
    "Badvel",
  ],
  keywords: [
    "tile store Jammalamadugu",
    "tiles showroom Jammalamadugu",
    "tile shop near Proddatur",
    "tiles Kadapa district",
    "vitrified tiles Andhra Pradesh",
    "bathware showroom Jammalamadugu",
    "Dream Home Enterprises",
    "dreamhomeenterprises.in",
  ],
};
